/** Ordered keyword → emoji lookup, most specific phrases first so e.g. "sweet potato" wins
 *  over the plain "potato" match beneath it. Food names come from free-text AI identification,
 *  so this is a best-effort visual stand-in, not an exact catalog lookup. */
const FOOD_EMOJI_RULES: [string, string][] = [
  ['avocado toast', '🥑'],
  ['peanut butter', '🥜'],
  ['ice cream', '🍦'],
  ['french fries', '🍟'],
  ['sweet potato', '🍠'],
  ['hot dog', '🌭'],
  ['bell pepper', '🫑'],
  ['orange juice', '🍊'],
  ['olive oil', '🫒'],
  ['bubble tea', '🧋'],

  ['avocado', '🥑'],
  ['banana', '🍌'],
  ['apple', '🍎'],
  ['pear', '🍐'],
  ['peach', '🍑'],
  ['mango', '🥭'],
  ['pineapple', '🍍'],
  ['watermelon', '🍉'],
  ['melon', '🍈'],
  ['papaya', '🍈'],
  ['guava', '🍈'],
  ['cantaloupe', '🍈'],
  ['apricot', '🍑'],
  ['prune', '🍇'],
  ['grape', '🍇'],
  ['cherry', '🍒'],
  ['cherries', '🍒'],
  ['strawberr', '🍓'],
  ['blueberr', '🫐'],
  ['kiwi', '🥝'],
  ['lemon', '🍋'],
  ['lime', '🍋'],
  ['coconut', '🥥'],
  ['pomegranate', '🍎'],
  ['orange', '🍊'],

  ['tomato', '🍅'],
  ['cucumber', '🥒'],
  ['carrot', '🥕'],
  ['onion', '🧅'],
  ['garlic', '🧄'],
  ['potato', '🥔'],
  ['corn', '🌽'],
  ['broccoli', '🥦'],
  ['cauliflower', '🥦'],
  ['mushroom', '🍄'],
  ['pumpkin', '🎃'],
  ['eggplant', '🍆'],
  ['pepper', '🫑'],
  ['lettuce', '🥬'],
  ['spinach', '🥬'],
  ['kale', '🥬'],
  ['cabbage', '🥬'],
  ['salad', '🥗'],
  ['ginger', '🫚'],
  ['leafy', '🥬'],
  ['sprout', '🥬'],
  ['asparagus', '🥬'],
  ['parsley', '🌿'],
  ['seaweed', '🌿'],

  ['egg', '🥚'],
  ['turkey', '🦃'],
  ['poultry', '🍗'],
  ['chicken', '🍗'],
  ['organ meat', '🥩'],
  ['red meat', '🥩'],
  ['beef', '🥩'],
  ['steak', '🥩'],
  ['bacon', '🥓'],
  ['pork', '🥓'],
  ['meat', '🥩'],
  ['salmon', '🐟'],
  ['tuna', '🐟'],
  ['sardine', '🐟'],
  ['mackerel', '🐟'],
  ['trout', '🐟'],
  ['cod', '🐟'],
  ['fish', '🐟'],
  ['oyster', '🦪'],
  ['clam', '🦪'],
  ['shellfish', '🦐'],
  ['shrimp', '🍤'],
  ['prawn', '🍤'],
  ['lentil', '🫘'],
  ['legume', '🫘'],
  ['bean', '🫘'],
  ['chickpea', '🫘'],
  ['hummus', '🫘'],
  ['quinoa', '🌾'],
  ['grain', '🌾'],

  ['rice', '🍚'],
  ['noodle', '🍜'],
  ['ramen', '🍜'],
  ['spaghetti', '🍝'],
  ['pasta', '🍝'],
  ['bread', '🍞'],
  ['toast', '🍞'],
  ['bagel', '🥯'],
  ['sandwich', '🥪'],
  ['burger', '🍔'],
  ['pizza', '🍕'],
  ['taco', '🌮'],
  ['burrito', '🌯'],
  ['sushi', '🍣'],
  ['dumpling', '🥟'],
  ['soup', '🍲'],
  ['stew', '🍲'],
  ['curry', '🍛'],
  ['pancake', '🥞'],
  ['waffle', '🧇'],
  ['cereal', '🥣'],
  ['oat', '🥣'],
  ['yogurt', '🥛'],
  ['milk', '🥛'],
  ['dairy', '🥛'],
  ['cheese', '🧀'],
  ['butter', '🧈'],
  ['salt', '🧂'],

  ['cake', '🍰'],
  ['cookie', '🍪'],
  ['donut', '🍩'],
  ['doughnut', '🍩'],
  ['muffin', '🧁'],
  ['cupcake', '🧁'],
  ['chocolate', '🍫'],
  ['candy', '🍬'],
  ['popcorn', '🍿'],
  ['chips', '🥔'],
  ['pretzel', '🥨'],
  ['croissant', '🥐'],
  ['pastry', '🥐'],

  ['coffee', '☕'],
  ['tea', '🍵'],
  ['juice', '🧃'],
  ['soda', '🥤'],
  ['smoothie', '🥤'],
  ['wine', '🍷'],
  ['beer', '🍺'],

  ['almond', '🥜'],
  ['walnut', '🌰'],
  ['cashew', '🥜'],
  ['peanut', '🥜'],
  ['pistachio', '🌰'],
  ['nut', '🥜'],
  ['seed', '🌱'],
]

const DEFAULT_MEAL_EMOJI = '🍽️'

/** Best-effort emoji for a free-text food name, matched by keyword. Falls back to a plate icon. */
export function resolveFoodEmoji(name: string | undefined): string {
  if (!name) return DEFAULT_MEAL_EMOJI
  const lower = name.toLowerCase()
  for (const [keyword, emoji] of FOOD_EMOJI_RULES) {
    if (lower.includes(keyword)) return emoji
  }
  return DEFAULT_MEAL_EMOJI
}
